# Generated by Django 4.2.2 on 2023-06-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='desc',
            field=models.TextField(default='Too much of a yummy thing is a bad thing'),
        ),
    ]
